# Generated by Django 6.0.4 on 2026-07-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='max_attendance_cost',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
