# Generated by Django 6.0.4 on 2026-07-17 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('is_private', models.BooleanField()),
                ('scholarships', models.BooleanField()),
                ('application_deadline', models.DateField()),
                ('early_action', models.BooleanField()),
                ('early_decision', models.BooleanField()),
                ('essays_count', models.IntegerField()),
                ('competencies', models.JSONField(default=list)),
                ('attendance_cost', models.IntegerField()),
                ('acceptance_rate', models.IntegerField()),
                ('AP_exams', models.BooleanField()),
                ('min_GPA', models.FloatField()),
                ('description', models.CharField(max_length=1000)),
                ('majors', models.JSONField()),
            ],
        ),
    ]
